# -*- mode: python ; coding: utf-8 -*-
# HALbasic PyInstaller Spec File
# Generated by create_installer.py

import sys
from pathlib import Path

block_cipher = None

APP_NAME = 'HALbasic'
APP_VERSION = '0.0.1'
COMPANY = 'gobioeng.com'
DESCRIPTION = 'Professional LINAC Water System Monitor'

a = Analysis(
    ['main.py'],
    pathex=['/home/runner/work/HALbasic/HALbasic'],
    binaries=[],
    datas=[('/home/runner/work/HALbasic/HALbasic/data', 'data'), ('/home/runner/work/HALbasic/HALbasic/assets', 'assets'), ('/home/runner/.local/lib/python3.12/site-packages/matplotlib/mpl-data', 'matplotlib/mpl-data'), ('/home/runner/.config/matplotlib', 'matplotlib/config')],
    hiddenimports=['PyQt5.QtCore', 'PyQt5.QtGui', 'PyQt5.QtWidgets', 'matplotlib.backends.backend_qt5agg', 'matplotlib.backends.backend_pdf', 'matplotlib.backends._backend_qt5', 'matplotlib.backends.backend_agg', 'matplotlib.figure', 'matplotlib.dates', 'matplotlib.pyplot', 'matplotlib._path', 'matplotlib.ft2font', 'matplotlib.style', 'matplotlib.font_manager', 'pandas', 'numpy', 'scipy', 'pyqtgraph'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter', 'tk', 'tcl',
        'PIL', 'Pillow',
        'test', 'tests',
        'distutils',
        'setuptools',
        '_pytest',
        'pytest',
        'sphinx',
        'IPython',
        'jupyter',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(
    a.pure,
    a.zipped_data,
    cipher=block_cipher
)

# Build type selection

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name=APP_NAME,
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    version='version_info.txt',
    icon='assets/halogo.ico'
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name=APP_NAME,
)
